CREATE TABLE IF NOT EXISTS portal_site_settings (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    content_json LONGTEXT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='门户站点设置';
